export enum UserEventStatus {
  ATTENDING = 'ATTENDING',
  MAYBE_ATTENDING = 'MAYBE ATTENDING',
  NOT_ATTENDING = 'NOT ATTENDING',
  PENDING_CONFIRMATION = 'PENDING',
  CANCELED = 'CANCELED',
  INVITED = 'INVITED',
}
